<?php

$labels = array();
$labels['forward'] = 'Forwarding';
$labels['forwardenable'] = 'Enable';
$labels['forwardsubject'] = 'Subject:';
$labels['forwardmessage'] = 'Message:';
$labels['forwardforwarder'] = 'Forward address:';
$labels['forwardstart'] = 'Start:';
$labels['forwardend'] = 'End:';
$labels['forwardkeepcopyininbox'] = 'Keep copy in inbox';

$messages = array();
$messages['forwardinvalidstartdate'] = 'Please select a valid start date.';
$messages['forwardinvalidenddate'] = 'Please select a valid end date.';
$messages['forwardinvaliddateinterval'] = 'The date interval is not valid.';
$messages['forwardnosubject'] = 'Please fill the subject of your forward.';
$messages['forwardnomessage'] = 'Please fill the message of your forward.';
$messages['forwardinvalidforwarder'] = 'The forward address is not valid.';
$messages['forwardinvalidforwarders'] = 'The forward addresses list is not valid.';
$messages['forwarddriverdefaulterror'] = 'Unknown execution error';
$messages['forwarddriverconnecterror'] = 'Error during connection';
$messages['forwarddriverprocesserror'] = 'Error during processing';
